apiVersion: v1
kind: Service
metadata:
  name: miniapp-usermanagementdb
  namespace: miniapp
spec:
  selector:
    app: usermanagement-dbapp
  ports:
    - port: 5433
      targetPort: 5432
  type: ClusterIP
