apiVersion: v1
kind: Service
metadata:
  name: miniapp-usermanagement-service
  namespace: miniapp
spec:
  selector:
    app: usermanagement-app
  ports:
    - port: 5001
      targetPort: 9091
  type: LoadBalancer
