apiVersion: apps/v1
kind: Deployment
metadata:
  name:  miniapp-registration
  namespace: miniapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-app
  template:
    metadata:
      labels:
        app: registration-app
    spec:
      containers:
        - name: reg-app
          image: registration:v1
          ports:
            - containerPort: 9091
          envFrom:
            - configMapRef:
                name: miniapp-registration-configmap
          resources:
            requests:
              memory: "256Mi"  
              cpu: "100m"     
            limits:
              memory: "512Mi"  
              cpu: "200m"