apiVersion: v1
kind: Service
metadata:
  name: miniapp-registration-service
  namespace: miniapp
spec:
  selector:
    app: registration-app
  ports:
    - port: 5001
      targetPort: 9091
  type: LoadBalancer
