apiVersion: v1
kind: Service
metadata:
  name: registrations-service
  namespace: miniapp
spec:
  selector:
    app: registrations-service
  ports:
    - port: 5001
      targetPort: 9091
  type: LoadBalancer
