apiVersion: v1
kind: Service
metadata:
  name: miniapp-registrationdb
  namespace: miniapp
spec:
  selector:
    app: registration-dbapp
  ports:
    - port: 5433
      targetPort: 5432
  type: ClusterIP
