apiVersion: apps/v1
kind: Deployment
metadata:
  name: authtokens-service-deployment
  namespace: miniapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authtokens-service
  template:
    metadata:
      labels:
        app: authtokens-service
    spec:
      containers:
        - name: authtokens-app
          image: authtokens:v1
          ports:
            - containerPort: 9093
          envFrom:
            - configMapRef:
                name: authtokens-configmap