apiVersion: v1
kind: Service
metadata:
  name: authtokens-service
  namespace: miniapp
spec:
  selector:
    app: authtokens-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 9093
  type: LoadBalancer
