apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniapp-authtoken
  namespace: miniapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authtoken-app
  template:
    metadata:
      labels:
        app: authtoken-app
    spec:
      containers:
        - name: token-app
          image: authtoken:v1
          ports:
            - containerPort: 9093
          envFrom:
            - configMapRef:
                name: miniapp-authtoken-configmap
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"