apiVersion: v1
kind: Service
metadata:
  name: miniapp-authtoken-service
  namespace: miniapp
spec:
  selector:
    app: authtoken-app
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 9093
  type: LoadBalancer
